spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update         # 초기에만 사용, 이후 Flyway로 전환
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 8MB        # 파일 하나의 최대 크기
      max-request-size: 30MB    # 전체 요청 최대 크기

server:
  port: 8080
  address: 0.0.0.0
  forward-headers-strategy: framework

guiro:
  vision:
    base-url: http://127.0.0.1:8000
    token: dev-shared-token
    connect-timeout-ms: 5000
    read-timeout-ms: 5000
  tour:
    base-url: https://apis.data.go.kr/B551011/KorService2
    service-key: ${TOUR_API_SERVICE_KEY}
    check-radius-meters: 5000
  jwt:
    private-key-location: "file:/home/ec2-user/app/keys/private.pem"
    public-key-location: "file:/home/ec2-user/app/keys/public.pem"


auth:
  jwt:
    issuer: site.guiro.api
    access-token-ttl: PT1H
    refresh-token-ttl: P30D
